DROP TABLE IF EXISTS "Tasks";
DROP TABLE IF EXISTS "Users";

CREATE TABLE "Users" (
  user_id BIGINT NOT NULL UNIQUE,
  username CHARACTER VARYING(16) NOT NULL UNIQUE,
  email CHARACTER VARYING(128) UNIQUE,
  timezone CHARACTER (3),
  password_hash CHARACTER VARYING(256) NOT NULL UNIQUE,
  PRIMARY KEY (user_id)
);

CREATE TABLE "Tasks" (
  task_id SERIAL NOT NULL UNIQUE,
  user_id INT NOT NULL,
  title CHARACTER VARYING(32) NOT NULL,
  description TEXT,
  send_email BOOLEAN NOT NULL,
  state CHARACTER(1) NOT NULL,
  start_date TIMESTAMP WITH TIME ZONE NOT NULL,
  end_date TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY (task_id),
  CONSTRAINT FK_user FOREIGN KEY(user_id)
    REFERENCES "Users"(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);
